DC-SWAT/DreamShell

- applications/iso_loader/modules/module.c
Fix Bug Address Memory IsoLoader
> Fix Bug Address Memory IsoLoader

- applications/games_menu/modules/app_definition.h
- applications/games_menu/modules/module.c
Fix memory when games is loaded
Change OPT to GDI
> [Games Menu] - Fix memory and Change OPT to GDI

- sdk/bin/src/img4dc/CMakeLists.txt
- sdk/bin/src/img4dc/mds4dc/src/tools.c
- realpath() function requires: -D_XOPEN_SOURCE=500
- mds4ds requires <string.h>
> img4dc: buildfixes

- sdk/bin/src/img4dc/mds4dc/src/tools.c
Should have been <strings.h> instead of <string.h>
> img4dc: mds4dc small typo

- applications/games_menu/modules/module.c
- applications/games_menu/modules/preset.c
Comments and position adjustments in controls.
> [games-menu] - Minor adjustments

- applications/games_menu/modules/app_definition.h
> [games_menu] - fix preset name

- applications/games_menu/modules/menu.c
- applications/games_menu/modules/module.c
- applications/games_menu/modules/preset.c
- applications/games_menu/modules/system_menu.c
- applications/games_menu/modules/utils.c
> [games_menu] - remove stop track

- applications/games_menu/modules/menu.c
- lib/libtsunami/src/drawables/form.cpp
- src/img/convert.c
- src/img/copy.c
- src/img/decode.c
- src/img/utils.c
Hi Swat,
Please give it a review, it no longer shows errors to me with have 138 games, I hope it doesn't to you either, it still needs to give it performance.
> [games_menu] - Fix extract covers

- applications/games_menu/modules/app_system_menu.h
- applications/games_menu/modules/menu.c
- applications/games_menu/modules/system_menu.c
- exports.txt
- include/tsunami/drawables/form.h
- lib/libtsunami/src/drawables/form.cpp
- src/utils.c
+ Fix cursor position in label control.
+ O_TRUNC in CopyFile
> [games_menu] - fix cursor

- applications/games_menu/Makefile
> [games_menu] - remove presets folder from make file

- applications/games_menu/modules/app_definition.h
- applications/games_menu/modules/app_menu.h
- applications/games_menu/modules/app_system_menu.h
- applications/games_menu/modules/menu.c
- applications/games_menu/modules/module.c
- applications/games_menu/modules/system_menu.c
- lib/libtsunami/src/drawables/checkbox.cpp
- lib/libtsunami/src/drawables/form.cpp
- lib/libtsunami/src/drawables/itemmenu.cpp
- lib/libtsunami/src/drawables/label.cpp
- lib/libtsunami/src/drawables/optiongroup.cpp
- lib/libtsunami/src/drawables/textbox.cpp
- new option for change page in menu with left and rigth pad
- stabilization controlls
> [games-menu] - moving menu with pad and stabilization controlls

- applications/games_menu/modules/system_menu.c
- lib/libtsunami/src/drawable.cpp
- lib/libtsunami/src/drawables/checkbox.cpp
- lib/libtsunami/src/drawables/form.cpp
- lib/libtsunami/src/drawables/optiongroup.cpp
- lib/libtsunami/src/drawables/scene.cpp
- lib/libtsunami/src/drawables/textbox.cpp
- lib/libtsunami/src/dsapp.cpp
fix video synchronization and minor adjustments
> [games-menu] - video synchronization

- applications/games_menu/modules/utils.c
Fix bug detected IsGdiOptimized
> [games-menu] - bug detected IsGdiOptimized

- applications/games_menu/modules/app_definition.h
- applications/games_menu/modules/menu.c
- applications/games_menu/modules/utils.c
- applications/iso_loader/modules/utils.c
- lib/libtsunami/src/drawables/itemmenu.cpp
Fix Bug detected when preset does not exist.
> [games-menu] - Bug detected when preset does not exist.

- applications/games_menu/modules/app_menu.h
- applications/games_menu/modules/menu.c
- applications/games_menu/modules/module.c
- applications/games_menu/modules/utils.c
- lib/libtsunami/src/drawables/form.cpp
> [games-menu] - fix firmware sort

- applications/games_menu/modules/menu.c
- src/img/convert.c
- src/img/decode.c
- src/img/utils.c
+ Possible fix when extracting covers.
> [app-games-menu] - Optimized code for cover extraction

- applications/games_menu/modules/module.c
- lib/libtsunami/src/animation.cpp
- lib/libtsunami/src/genmenu.cpp
layout adjustment and video lock
> [app-games-menu] - layout adjustment and video lock

- applications/games_menu/modules/menu.c
- applications/iso_loader/modules/module.c
> [app-games-menu] - Fix VMU binding

- applications/games_menu/modules/preset.c
- lib/libtsunami/src/drawable.cpp
- lib/libtsunami/src/drawables/banner.cpp
- lib/libtsunami/src/drawables/itemmenu.cpp
performance and vmu temporary option
> [app-games-menu] -  performance and vmu temporary option

- applications/games_menu/modules/preset.c
- lib/libtsunami/src/drawables/itemmenu.cpp
+ Fix cover banner
+ ItemMenu, just code identification
> [app-games-menu] - Fix cover banner and code identification

- applications/games_menu/modules/app_definition.h
- applications/games_menu/modules/menu.c
- applications/games_menu/modules/preset.c
- applications/games_menu/modules/system_menu.c
+ check irq option
+ cut text messages in optimization/extracting covers
> [app-games-menu] - cut text messages and check irq option.

- applications/games_menu/modules/preset.c
+ Changes async text depending on DMA
> [app-games-menu] - dma option text

- applications/games_menu/modules/menu.c
- applications/games_menu/modules/preset.c
> [app-games-menu] - fix custom memory

- applications/games_menu/modules/app_definition.h
- applications/games_menu/modules/menu.c
- applications/games_menu/modules/module.c
- applications/games_menu/modules/preset.c
+  performance on loading games
+ center preset screen
> [app-games-menu] - performance on load and center preset screen

- applications/games_menu/modules/menu.c
- applications/games_menu/modules/module.c
+ minor performance tweaks
Its Ready
> [app-games-menu] - minor performance tweaks

- applications/games_menu/modules/menu.c
- applications/games_menu/modules/preset.c
- include/tsunami/drawables/form.h
- lib/libtsunami/src/drawables/form.cpp
> [app-games-menu] - some fixes in ui and lib

- lib/libtsunami/src/drawables/form.cpp
+ fix random crashes when closing presets
> [app-games-menu] - fix random crashes when closing presets

- applications/games_menu/modules/module.c
+ fix the error when there are no games
> [app-games-menu] - fix the error when there are no games

- applications/games_menu/modules/app_definition.h
- applications/games_menu/modules/app_menu.h
- applications/games_menu/modules/app_system_menu.h
- applications/games_menu/modules/menu.c
- applications/games_menu/modules/module.c
- applications/games_menu/modules/preset.c
- applications/games_menu/modules/system_menu.c
- exports.txt
- include/tsunami/drawables/rectangle.h
- lib/libtsunami/src/drawables/form.cpp
- lib/libtsunami/src/drawables/rectangle.cpp
+ added option start last game played
> [app-games-menu] - added option start last game played, design, fix bugs forms and presets

- applications/games_menu/modules/menu.c
- applications/games_menu/modules/module.c
Fix playing CDDA 
Sort Categories
> [games-menu] - Fix CDDA bug, last game played bug and sort categories

- applications/games_menu/modules/module.c
Fix total legends on theme refresh
> [games-menu] - Fix total legends on theme refresh

- applications/main/modules/module.c
Scroll screen with left and right triggers
> Scroll screen with left and right triggers

- applications/main/app.xml
- applications/main/modules/app_module.h
- applications/main/modules/exports.txt
- applications/main/modules/module.c
Unload event on main app close
> Unload event on main app close

- applications/games_menu/modules/system_menu.c
> [games-menu] - create cache if necessary

- include/tsunami/anims/fadein.h
- include/tsunami/anims/fadeout.h
- include/tsunami/anims/fadeto.h
- include/tsunami/drawables/box.h
- include/tsunami/drawables/checkbox.h
- include/tsunami/drawables/combobox.h
- include/tsunami/drawables/optiongroup.h
- include/tsunami/drawables/rectangle.h
- include/tsunami/drawables/textbox.h
- include/tsunami/drawables/triangle.h
- include/tsunami/dsapp.h
- include/tsunami/inputeventstate.h
- include/tsunami/tsudefinition.h
- include/tsunami/tsunami.h
- include/tsunami/tsunamiutils.h
- lib/libtsunami/src/anims/fadein.cpp
- lib/libtsunami/src/anims/fadeout.cpp
- lib/libtsunami/src/anims/fadeto.cpp
- lib/libtsunami/src/drawables/checkbox.cpp
- lib/libtsunami/src/drawables/form.cpp
- lib/libtsunami/src/drawables/optiongroup.cpp
- lib/libtsunami/src/drawables/rectangle.cpp
- lib/libtsunami/src/drawables/textbox.cpp
- lib/libtsunami/src/dsapp.cpp
- lib/libtsunami/src/tsunamiutils.cpp
Comment adjustments and removal of unnecessary code.
> [tsunami-lib] - Comment adjustments and removal of unnecessary code.

- applications/games_menu/modules/menu.c
- applications/games_menu/modules/module.c
Removed thd_sleep to improve cursor scrolling and when displaying images.
> [games-menu] - improved cursor movement and image cover

- applications/games_menu/modules/app_utils.h
- applications/games_menu/modules/menu.c
- applications/games_menu/modules/utils.c
> [games-menu] - presets romdisk support

- applications/games_menu/modules/module.c
- lib/libtsunami/src/drawables/form.cpp
- added when moving between games
- It adapts when changing pages but is disabled
> [games-menu] - adapted sfx

- applications/games_menu/modules/module.c
- applications/games_menu/modules/preset.c
- applications/games_menu/modules/system_menu.c
- exports.txt
- include/sfx.h
- include/tsunami/drawables/form.h
- lib/libtsunami/src/drawables/form.cpp
- src/sfx.c
added internal sfx 
more sfx in games menu
> [tsunami] - added internal sfx and more sfx in games menu

- applications/games_menu/modules/app_menu.h
- applications/games_menu/modules/menu.c
> [games_menu] - Fix Showing Covers

- applications/games_menu/modules/app_definition.h
- applications/games_menu/modules/app_menu.h
- applications/games_menu/modules/menu.c
- applications/games_menu/modules/module.c
- modules/ffmpeg/player.c
+ FFMPEG support for games_menu
> FFMPEG support for games_menu

- applications/games_menu/modules/menu.c
- applications/games_menu/modules/module.c
fix bug to change view with trailer actived
> [games-menu] - fix bug to change view
